/*
 * Copyright (c) 2016-2022 Marco Cawthorne <marco@icculus.org>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF MIND, USE, DATA OR PROFITS, WHETHER
 * IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
 * OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

enum
{
	TFCANIM_DIEGUTSHOT = ANIM_DIEGUTSHOT,
	TFCANIM_AIMCROWBAR,
	TFCANIM_SHOOTCROWBAR,
	TFCANIM_CR_AIMCROWBAR,
	TFCANIM_CR_SHOOTCROWBAR,
	TFCANIM_AIM1HAND,
	TFCANIM_SHOOT1HAND,
	TFCANIM_CR_AIM1HAND,
	TFCANIM_CR_SHOOT1HAND,
	TFCANIM_AIMSHOTGUN,
	TFCANIM_SHOOTSHOTGUN,
	TFCANIM_CR_AIMSHOTGUN,
	TFCANIM_CR_SHOOTSHOTGUN,
	TFCANIM_AIMGAUSS,
	TFCANIM_SHOOTGAUSS,
	TFCANIM_CR_AIMGAUSS,
	TFCANIM_CR_SHOOTGAUSS,
	TFCANIM_AIMMP5,
	TFCANIM_SHOOTMP5,
	TFCANIM_CR_AIMMP5,
	TFCANIM_CR_SHOOTMP5,
	TFCANIM_AIMRPG,
	TFCANIM_SHOOTRPG,
	TFCANIM_CR_AIMRPG,
	TFCANIM_CR_SHOOTRPG,
	TFCANIM_AIMEGON,
	TFCANIM_SHOOTEGON,
	TFCANIM_CR_AIMEGON,
	TFCANIM_CR_SHOOTEGON,
	TFCANIM_AIMSNIPER,
	TFCANIM_SHOOTSNIPER,
	TFCANIM_CR_AIMSNIPER,
	TFCANIM_CR_SHOOTSNIPER,
	TFCANIM_AIMAUTOSNIPER,
	TFCANIM_SHOOTAUTOSNIPER,
	TFCANIM_CR_AIMAUTOSNIPER,
	TFCANIM_CR_SHOOTAUTOSNIPER,
	TFCANIM_AIMMEDKIT,
	TFCANIM_SHOOTMEDKIT,
	TFCANIM_CR_AIMMEDKIT,
	TFCANIM_CR_SHOOTMEDKIT,
	TFCANIM_AIMKNIFE,
	TFCANIM_SHOOTKNIFE,
	TFCANIM_CR_AIMKNIFE,
	TFCANIM_CR_SHOOTKNIFE,
	TFCANIM_AIMASSCAN,
	TFCANIM_SHOOTASSCAN,
	TFCANIM_CR_AIMASSCAN,
	TFCANIM_CR_SHOOTASSCAN
};