/*
 * Copyright (c) 2016-2020 Marco Cawthorne <marco@icculus.org>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF MIND, USE, DATA OR PROFITS, WHETHER
 * IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
 * OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

/* weapon Indices for the weapon table */
enum
{
	WEAPON_NONE,
	WEAPON_CROWBAR,
	WEAPON_MEDKIT,
	WEAPON_KNIFE,
	WEAPON_WRENCH,
	WEAPON_UMBRELLA,
	WEAPON_SBS,
	WEAPON_SNIPER,
	WEAPON_TRANQUIL,
	WEAPON_RAILGUN,
	WEAPON_AUTORIFLE,
	WEAPON_DBS,
	WEAPON_NAILGUN,
	WEAPON_GLAUNCHER,
	WEAPON_SUPERNAIL,
	WEAPON_FLAMER,
	WEAPON_RPG,
	WEAPON_PIPEBOMB,
	WEAPON_ASSCAN,
	WEAPON_INCENDIARY,
	WEAPON_GRAPPLE
};


#define WEIGHT_CROWBAR -1
#define WEIGHT_MEDKIT 1
#define WEIGHT_KNIFE 1
#define WEIGHT_WRENCH 1
#define WEIGHT_UMBRELLA 1
#define WEIGHT_SBS 10
#define WEIGHT_SNIPER 10
#define WEIGHT_TRANQUIL 10
#define WEIGHT_RAILGUN 10
#define WEIGHT_AUTORIFLE 10
#define WEIGHT_DBS 20
#define WEIGHT_NAILGUN 20
#define WEIGHT_GLAUNCHER 20
#define WEIGHT_SUPERNAIL 20
#define WEIGHT_FLAMER 20
#define WEIGHT_RPG 20
#define WEIGHT_PIPEBOMB 0
#define WEIGHT_ASSCAN 20
#define WEIGHT_INCENDIARY 20
#define WEIGHT_GRAPPLE -1